### ISSUE TITLE
500 raised on saving proposal

### ISSUE THREAD

**Issue by aarose** [pyconca/2016-symposion#3]
Created a test proposal, and submitted just fine the first time.

Then tried to upload a file, and got a 500. Now, I consistently get a 500 when I try to re-save the proposal.

<img width="637" alt="screen shot 2016-07-27 at 3 56 30 pm" src="https://cloud.githubusercontent.com/assets/2035914/17190296/5ebb628e-5413-11e6-8678-1a44aaad77fc.png">

|
|
|

<img width="636" alt="screen shot 2016-07-27 at 3 56 42 pm" src="https://cloud.githubusercontent.com/assets/2035914/17190301/61e11e4a-5413-11e6-8274-5ea19888db69.png">

Update: Now I get a 500 when even trying to see the proposal again.

**Comment by myles** [comment]
This was fixed by creating the `media` directory on the server and making sure the `deploy` user has access.
